# Generated by Django 2.1.8 on 2020-08-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200825_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
